src/main/java/org/b3log/symphony/processor/AdminProcessor.java
=> fix: 防止管理员给自己刷功德积分

src/main/resources/skins/classic/index.ftl
=> 🎨 首页聊天室@功能

src/main/java/org/b3log/symphony/processor/TagProcessor.java, src/main/resources/skins/classic/common/person-info.ftl, src/main/resources/skins/classic/tags.ftl
=> 🎨 标签页 样式优化与关注功能

src/main/java/org/b3log/symphony/processor/ChatroomProcessor.java, src/main/resources/local.properties
=> fix: 解决去重失效的bug

src/main/resources/lang_en_US.properties, src/main/resources/lang_zh_CN.properties, src/main/resources/skins/classic/chat-room.ftl, src/main/resources/skins/mobile/chat-room.ftl
=> :art:增加清屏按钮，卡死了

src/main/resources/skins/classic/common/comment.ftl
=> style: 优化勋章在评论区的位置

src/main/java/org/b3log/symphony/processor/ChatroomProcessor.java, src/main/resources/js/chat-room.js
=> feat: 红包分类:普通红包|拼手气红包

src/main/java/org/b3log/symphony/processor/CloudProcessor.java, src/main/java/org/b3log/symphony/processor/TopProcessor.java, src/main/java/org/b3log/symphony/service/ActivityQueryService.java, src/main/java/org/b3log/symphony/service/CloudService.java, src/main/resources/skins/classic/games/evolve/index.ftl, src/main/resources/skins/classic/top/evolve.ftl, src/main/resources/skins/mobile/games/evolve/index.ftl, src/main/resources/skins/mobile/top/evolve.ftl
* evolve 版本更新至v1.2.0
* 需要清理删除symphony_cloud gameId=40 原采集数据
* 需要清理原sync采集interval，新采集interval位于games/evolve/index.ftl#148
=> :art: 更新优化进化排行榜

src/main/java/org/b3log/symphony/processor/CloudProcessor.java, src/main/java/org/b3log/symphony/processor/TopProcessor.java, src/main/java/org/b3log/symphony/service/ActivityQueryService.java, src/main/java/org/b3log/symphony/service/CloudService.java, src/main/resources/skins/classic/games/evolve/index.ftl, src/main/resources/skins/classic/top/evolve.ftl, src/main/resources/skins/mobile/games/evolve/index.ftl, src/main/resources/skins/mobile/top/evolve.ftl
=> Revert ":art: 更新优化进化排行榜"

src/main/java/org/b3log/symphony/processor/CloudProcessor.java, src/main/java/org/b3log/symphony/processor/TopProcessor.java, src/main/java/org/b3log/symphony/service/ActivityQueryService.java, src/main/java/org/b3log/symphony/service/CloudService.java, src/main/resources/skins/classic/top/evolve.ftl, src/main/resources/skins/mobile/top/evolve.ftl
fix problem of #26 `Cannot read properties of undefined (reading 'global')`
需更新cdn代码中的interval
=> :art: 更新优化进化排行榜 fix problem

src/main/java/org/b3log/symphony/processor/ChatroomProcessor.java
=> 🎨 降低最大红包的大小

src/main/java/org/b3log/symphony/service/CloudService.java, src/main/resources/js/chat-room.js
=> :wrench: 修复堆叠并发出现覆盖

src/main/java/org/b3log/symphony/processor/ChatroomProcessor.java
=> 🎨不允许给自己单独发专属红包

src/main/java/org/b3log/symphony/model/Common.java, src/main/java/org/b3log/symphony/model/Sponsor.java, src/main/java/org/b3log/symphony/model/UserExt.java, src/main/java/org/b3log/symphony/processor/AdminProcessor.java, src/main/java/org/b3log/symphony/processor/ChatroomProcessor.java, src/main/java/org/b3log/symphony/processor/IndexProcessor.java, src/main/java/org/b3log/symphony/repository/SponsorRepository.java, src/main/java/org/b3log/symphony/service/DataModelService.java, src/main/java/org/b3log/symphony/service/SponsorService.java, src/main/java/org/b3log/symphony/service/UserQueryService.java, src/main/resources/repository.json, src/main/resources/skins/classic/charge-point.ftl
=> 🎨 社区捐赠持久化捐赠记录

src/main/java/org/b3log/symphony/Server.java, src/main/java/org/b3log/symphony/event/ChangeRoleHandler.java, src/main/java/org/b3log/symphony/service/ArticleMgmtService.java
=> 🎨 新人报道自动切换角色

src/main/java/org/b3log/symphony/event/ChangeRoleHandler.java
=> fix: 新人报道 -> 新人报到

src/main/java/org/b3log/symphony/service/ArticleQueryService.java, src/main/resources/skins/classic/common/list-item.ftl, src/main/resources/skins/mobile/macro-list.ftl
=> 问答贴显示是否被采纳

src/main/java/org/b3log/symphony/processor/ChatroomProcessor.java, src/main/resources/js/chat-room.js, src/main/resources/js/common.js, src/main/resources/skins/classic/chat-room.ftl, src/main/resources/skins/mobile/chat-room.ftl
=> feat: 石头剪刀布红包

src/main/resources/skins/classic/top/adr.ftl, src/main/resources/skins/classic/top/emoji.ftl, src/main/resources/skins/classic/top/evolve.ftl, src/main/resources/skins/classic/top/lifeRestart.ftl, src/main/resources/skins/classic/top/macro-top.ftl, src/main/resources/skins/mobile/top/adr.ftl, src/main/resources/skins/mobile/top/emoji.ftl, src/main/resources/skins/mobile/top/evolve.ftl, src/main/resources/skins/mobile/top/lifeRestart.ftl, src/main/resources/skins/mobile/top/macro-top.ftl
=> fix: 修复游戏排行榜title

src/main/java/org/b3log/symphony/processor/middleware/validate/UserRegisterValidationMidware.java
=> 🎨 修复重复手机号仍然发送验证码的BUG

src/main/java/org/b3log/symphony/processor/LoginProcessor.java
=> 🎨 完善登陆注册流程API

src/main/java/org/b3log/symphony/processor/ChatroomProcessor.java
=> #60  🔧 修复猜拳红包百分百胜率BUG

src/main/java/org/b3log/symphony/model/OpenApi.java, src/main/java/org/b3log/symphony/model/Permission.java, src/main/java/org/b3log/symphony/service/InitMgmtService.java, src/main/java/org/b3log/symphony/service/OpenApiQueryService.java, src/main/resources/repository.json
=> feat: bug fix

src/main/java/org/b3log/symphony/model/OpenApi.java, src/main/java/org/b3log/symphony/model/Permission.java, src/main/java/org/b3log/symphony/processor/OpenProcessor.java, src/main/java/org/b3log/symphony/service/InitMgmtService.java, src/main/resources/repository.json, src/main/resources/skins/classic/admin/open.ftl, src/main/resources/skins/mobile/open/macro-open.ftl
=> 现在可以全新数据库初始化了

src/main/java/org/b3log/symphony/processor/ArticleProcessor.java, src/main/java/org/b3log/symphony/processor/UserProcessor.java, src/main/java/org/b3log/symphony/util/DesensitizeUtil.java
=> 🎨 用户帖子和清风明月API

src/main/resources/js/chat-room.js
=> 咳咳，图片查看器只改了一半，忘记修改条件了

src/main/resources/scss/index.scss, src/main/resources/skins/classic/index.ftl
=> feat: 调整小日历

src/main/resources/js/chat-room.js
=> feat: 聊天室举报新增确认弹窗

src/main/java/org/b3log/symphony/processor/TopProcessor.java, src/main/resources/skins/classic/top/donate.ftl, src/main/resources/skins/classic/top/index.ftl, src/main/resources/skins/classic/top/macro-top.ftl, src/main/resources/skins/mobile/top/donate.ftl, src/main/resources/skins/mobile/top/index.ftl
=> feat: 新增金主爸爸排行榜

src/main/java/org/b3log/symphony/processor/ChatroomProcessor.java
=> 积分回收计划-2: 聊天室猜拳红包收税, 税费 2 个点

src/main/java/org/b3log/symphony/processor/ChatroomProcessor.java, src/main/java/org/b3log/symphony/processor/bot/ChatRoomBot.java
聊天室执法菜单增加全员禁言, 增加通知及其余互动通知场合的清屏使用 (Op 豁免全员禁言, 我狠起来连自己都 ban)
=> 聊天室执法菜单增加全员禁言

src/main/resources/js/chat-room.js
普通用户增加用户发言屏蔽功能, 清净页面. op 无效(毕竟要监督不法分子)
=> 聊天室 : 普通用户增加用户发言屏蔽

src/main/java/org/b3log/symphony/processor/ApiProcessor.java
=> 提供API接口, 获取最近20个注册用户.

src/main/java/org/b3log/symphony/processor/ApiProcessor.java
=> 提供API接口, 获取最近20个注册用户. 只获取用户名和昵称

src/main/java/org/b3log/symphony/service/ArticleQueryService.java, src/main/resources/skins/classic/footer.ftl, src/main/resources/skins/mobile/footer.ftl
=> #115 🔧 初始化热点文章不足14个导致报错

src/main/resources/js/chat-room.js, src/main/resources/scss/base.scss
=> 添加回复消息跳转功能

src/main/resources/js/channel.js
=> 修复猜拳红包被抢后无法点开的bug

src/main/java/org/b3log/symphony/processor/ArticleProcessor.java
=> 新用户首帖限制为新人报道, 增加宵禁下发帖间隔频率

src/main/java/org/b3log/symphony/processor/ArticleProcessor.java
=> 更新第一帖检查. 新人报道和新人报到标签都没有才拦截

src/main/resources/js/channel.js, src/main/resources/js/chat-room.js, src/main/resources/scss/base.scss, src/main/resources/skins/classic/chat-room.ftl
=> 用户消息捕获，指令消息捕获

src/main/java/org/b3log/symphony/util/NodeUtil.java
=> fix: 优化聊天室clear命令解析

src/main/resources/js/chat-room.js
=> 🐞 fix: 移除聊天室中“为他求情”链接
